### ISSUE TITLE
button component

### ISSUE THREAD

**Issue by HassanBahati** [javaScriptKampala/hacktoberfest-uganda#3]
we seek to avoid repetition of rebuilding a a button component every other time we have to add a button and have a reusable button component that can be called, and props passed to it.

bellow are some hints

- create a directory under components which will hold the button component.
- create a reusuable component to which we can pass props so as to modify the styles and behavior of the button.
- remove all buttons and replace them with the button component.

the props to be passed to the button component may include the following though not limited to only the following;

` loading label`
`variant`
`label`
`icon before`
`icon after`
`loading`
`disabled`
`width`
`onClick`
`text align`
`className`
`href`
`...props`

**Comment by parush-uppal** [comment]
Hi would like to work on the issue could you assign it to me

**Comment by parush-uppal** [comment]
Hi, raised the pull request for this issue please review.

**Comment by HassanBahati** [comment]
> 

alright @parush-uppal
